accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.login, name='accounts'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('cadaster/', views.cadaster, name='cadaster'),
    path('new-contact/', views.add_contact, name='new_contact'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agenda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from captcha.views import captcha_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('accounts.urls')),
    path('captcha/image/<str:key>/', captcha_image, name='captcha-image'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models
from django.core import validators
from django.utils import timezone
from django.contrib.auth.models import User


class Categoria(models.Model):
    categoria = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.categoria


class Contato(models.Model):
    user = models.ForeignKey(User, models.DO_NOTHING, name='User')
    nome = models.CharField(max_length=150, name='Nome')
    sobrenome = models.CharField(max_length=150, blank=True, name='Sobrenome')
    telefone = models.CharField(
        max_length=11, validators=[
            validators.RegexValidator('^[1-9]{2}?:\d{8}|\d{9}$')
        ],
        name='Telefone'
    )
    email = models.EmailField(
        validators=[validators.validate_email], name='Email'
    )
    data_de_criacao = models.DateTimeField(
        default=timezone.now, name='Data_de_criação'
    )
    descricao = models.TextField(blank=True, name='Descrição')
    categoria = models.ForeignKey(
        Categoria, models.DO_NOTHING, name='Categoria'
    )
    foto = models.ImageField(
        upload_to='img/%Y/%m/%d', blank=True, validators=[
            validators.FileExtensionValidator(['png', 'jpg', 'webp', 'jpeg'])
        ]
    )

    def __str__(self):
        return self.Nome
    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from .validators import validate_password, validate_username
from django.core.validators import validate_email
from django.contrib import messages
from django.contrib.auth.models import User
from homepage.models import Contato, Categoria
from . import validators
from datetime import datetime
from django.db.models import Q, functions, Value
from homepage.recaptcha import ReCaptcha

CAPTCHA = {'captcha': ReCaptcha()}


def login(request):
    if request.method == 'GET':
        return render(request, 'login.html', CAPTCHA)

    USERNAME = request.POST.get('username')
    PASSWORD = request.POST.get('password')
    user = auth.authenticate(request, username=USERNAME, password=PASSWORD)
    if user is None:
        messages.error(request, 'Usuário ou senha inválidos.')
        return render(request, 'login.html', CAPTCHA)

    CAPTCHA_ANSWER = ReCaptcha(request.POST)
    if not CAPTCHA_ANSWER.is_valid():
        messages.error(request, 'Captcha incorreto.')
        return render(request, 'login.html', CAPTCHA)

    auth.login(request, user)
    messages.success(request, f'Você entrou como "{user}"')
    return redirect('homepage')


def cadaster(request):
    if request.method == 'GET':
        return render(request, 'cad.html', CAPTCHA)
    
    USERNAME = request.POST.get('username')
    EMAIL = request.POST.get('email')
    PASSWORD = request.POST.get('password')
    PASSWORD_CONFIRM = request.POST.get('passconfirm')
    CAPTCHA_ANSWER = ReCaptcha(request.POST)
    try:
        validate_username(USERNAME)
        if User.objects.filter(username=USERNAME).exists():
            messages.error(request, 'Nome de usuário já existe.')
            return render(request, 'cad.html')

        validate_email(EMAIL)
        if User.objects.filter(email=EMAIL).exists():
            messages.error(request, 'E-mail já existe.')
            return render(request, 'cad.html')

        validate_password(PASSWORD, PASSWORD_CONFIRM)
        if not CAPTCHA_ANSWER.is_valid():
            messages.error(request, 'Captcha inválido.')
            return render(request, 'cad.html', CAPTCHA)

    except Exception as msg:
        msg = list(msg)
        messages.error(request, msg[0])
        return render(request, 'cad.html', CAPTCHA)

    user = User.objects.create_user(username=USERNAME, password=PASSWORD, email=EMAIL)
    user.save()
    messages.success(request, 'Cadastro realizado, você já pode fazer login.')
    return redirect('login')


@auth.decorators.login_required(redirect_field_name='login')
def add_contact(request):
    context = {'categorias': Categoria.objects.all()}
    context.update(CAPTCHA)
    if request.method == 'GET':
        return render(request, 'add_contact.html', context)
    
    NAME = request.POST.get('nome').strip().title()
    LASTNAME = request.POST.get('sobrenome').strip().title()
    PHONE = request.POST.get('telefone')
    EMAIL = request.POST.get('email')
    DESCRIPTION = request.POST.get('descricao')
    PHOTO = request.FILES.get('foto')
    CATEGORY = Categoria.objects.filter(
        categoria=request.POST.get('categoria')
    ).first()
    context.update({'captcha': ReCaptcha(request.POST)})

    try:
        validators.validate_new_contact(NAME, LASTNAME, PHONE, EMAIL)
    except Exception as msg:
        msg = list(msg)
        messages.error(request, msg[0])
        return render(request, 'add_contact.html', context)
    
    if not context['captcha'].is_valid():
        messages.error(request, 'Captcha incorreto.')
        return render(request, 'add_contact.html', context)


    FULLNAME_FIELD = functions.Concat('Nome', Value(' '), 'Sobrenome')
    FULLNAME_VALUE = NAME + ' ' + LASTNAME
    temp_full_name_contact_field = Contato.objects.annotate(fullname=FULLNAME_FIELD)
    contact_already_exists = temp_full_name_contact_field.filter(
       Q(fullname=FULLNAME_VALUE) | Q(Telefone=PHONE),  User=request.user
    ).exists()

    if contact_already_exists:
        messages.warning(request, 'Contato já existe.')
        return render(request, 'add_contact.html', context)
    
    new_contact = Contato.objects.create(
        User=request.user, Nome=NAME, Sobrenome=LASTNAME, Telefone=PHONE,
        Email=EMAIL, Descrição=DESCRIPTION, Categoria=CATEGORY, foto=PHOTO
    )
    new_contact.save()
    messages.success(request, 'Contato salvo com sucesso.')
    return redirect('homepage')


@auth.decorators.login_required(redirect_field_name='login')
def logout(request):
    auth.logout(request)
    return redirect('login')

accounts/templates/add_contact.html
{% extends 'base.html' %}
<title>{% block title %}Adicionar{% endblock title %}</title>
{% block content %}
<div class="container mt-5">
    <form action="{% url 'new_contact' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <table>
            {% include 'partials/_messages.html' %}
                <tr>
                    <th><label for="id_Nome">Nome:</label></th>
                    <td>
                        
                        <input style="background-color: #3B3B3B; color: white;" type="text" value="{{request.POST.nome}}" name="nome" maxlength="150" minlength="3" required id="id_Nome">
                        
                        
                    </td>
                </tr>

                <tr>
                    <th><label for="id_Sobrenome">Sobrenome:</label></th>
                    <td>
                        
                        <input style="background-color: #3B3B3B; color: white;" type="text" name="sobrenome" value="{{request.POST.sobrenome}}" maxlength="150" minlength="3" id="id_Sobrenome">
                        
                        
                    </td>
                </tr>

                <tr>
                    <th><label for="id_Telefone">Telefone:</label></th>
                    <td>
                        
                        <input style="background-color: #3B3B3B; color: white;" type="text" value="{{request.POST.telefone}}" name="telefone" maxlength="11" minlength="8" required id="id_Telefone">
                    </td>
                </tr>

                <tr>
                <th><label for="id_Email">Email:</label></th>
                <td>  
                    <input style="background-color: #3B3B3B; color: white;" type="email" name="email" value="{{request.POST.email}}" maxlength="254" required id="id_Email">
                </td>
            </tr>

            <tr>
                <th><label for="id_Descrição">Descrição:</label></th>
                <td>
                <textarea style="background-color: #3B3B3B; color: white;" name="descricao" cols="40" rows="6" id="id_Descrição">
                </textarea>
                </td>
            </tr>
            <tr>
                <th><label for="id_Categoria">Categoria:</label></th>
                <td>
                    <select style="background-color: #3B3B3B; color: white;" name="categoria" value="{{ categoria }}" required id="id_Categoria">
                        {% for categoria in categorias %}
                            <option {% if categoria == request.POST.categoria %}selected{% endif %} >
                                {{categoria}}
                            </option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <th><label for="id_foto">Foto:</label></th>
                <td >
                    <input type="file" name="foto" accept="image/*" id="id_foto">
                </td>
            </tr>
            {{captcha}}
            <tr>
                <td colspan="2" >
                    <button>Enviar
                </td>
            </tr>
        </table>
    </form>
</div>
{% endblock content %}

accounts/templates/cad.html
{% load static %}
<head>
    {% include 'partials/_head.html' %}
  <title>{% block title %}Cadastrar{% endblock title %}</title>
</head>
<body>
{% autoescape on %}
  {% if not user.is_authenticated %}
      <form id="register-form" method="post" class="mb-5" action="{% url 'cadaster' %}">{% csrf_token %}
        {% include 'partials/_messages.html' %}
        <div class="form-group">
          <label for="username">Nome de usuário:</label>
          <a href="{% url 'login' %}" style="margin-left: 47%;">Login</a>
          <input type="text" value="{{request.POST.username}}"class="form-control" id="username" name="username">
        </div>
        <div class="form-group">
          <label for="email">Endereço de e-mail:</label>
          <input type="email" value="{{request.POST.email}}" class="form-control" id="email" name="email">
        </div>
        <div class="form-group">
          <label for="password">Senha:</label>
          <input type="password" class="form-control" id="password" name="password">
        </div>
        <div class="form-group">
          <label for="confirm-password">Confirmar senha:</label>
          <input type="password" class="form-control" id="confirm-password" name="passconfirm">
          <div class="text-center mt-3">
            {{captcha}}
          </div>
        </div>
        <div class="from-group">
            <input class="btn-cad" type="submit" value="Cadastrar">
        </div>
      </form>
  {% else %}
      <div class="mt-5 ml-5">
        <p>
            Você ja está logado como <b>{{user}}</b> <a href="{% url 'homepage' %}">clique aqui</a> 
            para voltar a página inicial.
        </p>
      </div>
  {% endif %}
{% endautoescape %}
</body>

accounts/templates/login.html
<head>
    {% include 'partials/_head.html' %}
    <title>{% block title %}Login{% endblock title %}</title>
</head>
<body>
{% autoescape on %}
    {% if not user.is_authenticated %}
    <form id="login-form" method="post" action="{% url 'login' %}" enctype="multipart/form-data">{% csrf_token %}
        {% include 'partials/_messages.html' %}
        <label for="username">Nome de usuário:</label>
        <a href="{% url 'cadaster' %}" class="ml-5">Cadastrar</a>
        <input type="text" value="{{request.POST.username}}" id="username" name="username" placeholder="Insira seu nome de usuário">
        <br>
        <label for="password">Senha:</label>
        <input type="password" id="password" name="password" placeholder="Insira sua senha">
        {{captcha}}
        <br>
        <input type="submit" value="Entrar">
    </form>
    {% else %}
        <div class="mt-5 ml-5">
        <p>
            Você ja está logado como <strong>{{user}}</strong> <a href="{% url 'homepage' %}">clique aqui</a> 
            para voltar a página inicial.
        </p>
    </div>
    {% endif %}
{% endautoescape %}
</body>
</html>